### PR TITLE
[DOCS] Fixes tutorial link in reference architecture prereqs component

### LINKED ISSUE #4188: No "next" button in tutorial intro
**Describe the bug**
Users cannot proceed through the [getting started tutorial](https://docs.greatexpectations.io/docs/tutorials/getting_started/intro) due to the "Next" button missing.

**To Reproduce**
1. Go to https://docs.greatexpectations.io/docs/tutorials/getting_started/intro
2. See that there is a "Next" button mentioned, but nothing found and no ability to proceed in the tutorial.

**Expected behavior**
A next button to proceed through the tutorial.

**Environment (please complete the following information):**
Google Chrome Version 95.0.4638.54 (Official Build) (x86_64)

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by austiezr**
Please annotate your PR title to describe what the PR does, then give a brief bulleted description of your PR below. PR titles should begin with [BUGFIX], [FEATURE],  [DOCS], or [MAINTENANCE]. If a new feature introduces breaking changes for the Great Expectations API or configuration files, please also add [BREAKING]. You can read about the tags in our [contributor checklist](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html).

Changes proposed in this pull request:
- Changes prereqs for deployment patterns to point to the new tutorial

After submitting your PR, CI checks will run and @ge-cla-bot will check for your CLA signature.

For a PR with nontrivial changes, we review with both design-centric and code-centric lenses.

In a design review, we aim to ensure that the PR is consistent with our relationship to the open source community, with our software architecture and abstractions, and with our users' needs and expectations. That review often starts well before a PR, for example in github issues or slack, so please link to relevant conversations in notes below to help reviewers understand and approve your PR more quickly (e.g. `closes #123`).

Previous Design Review notes:
- Closes #4188 

### Definition of Done
Please delete options that are not relevant.

- [x] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/docs/contributing/style_guides/code_style)
- [x] I have performed a [self-review](https://docs.greatexpectations.io/docs/contributing/contributing_checklist) of my own code
- [x] I have made corresponding changes to the documentation
- [x] I have run any local integration tests and made sure that nothing is broken.

Thank you for submitting!

### CODE REVIEW

File: docs/deployment_patterns/components/deployment_pattern_prerequisites.jsx [hunk 1]
```diff
@@ -32,7 +32,7 @@ export default class Prerequisites extends React.Component {
 
   defaultPrerequisiteItems () {
     return [
-      <li key={0.1}>Completed the <a href='/docs/tutorials/getting_started/intro'>Getting Started Tutorial</a></li>
+      <li key={0.1}>Completed the <a href='docs/tutorials/getting_started/tutorial_overview'>Getting Started Tutorial</a></li>
```
Comment (Rachel-Reverie) [inline docs/deployment_patterns/components/deployment_pattern_prerequisites.jsx]: The link as it is currently won't direct to where you want it to --It will be treated as a relative link, so it'll end up pointing to `docs/deployment_patterns/components/docs/getting_started/tutorial_overview`.  Instead, you'll want to keep the leading / so that it is treated as an absolute path from the root, which should render as `/docs/tutorials/getting_started/tutorial_overview/`

```suggestion
      <li key={0.1}>Completed the <a href='/docs/tutorials/getting_started/tutorial_overview'>Getting Started Tutorial</a></li>
```

**Review by Rachel-Reverie — CHANGES_REQUESTED** [review]

**Review by Rachel-Reverie — APPROVED** [review]
The updated links look good to me.
